from __future__ import annotations

import json
from pathlib import Path


def _code_cell(source: str) -> dict:
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [line + "\n" for line in source.strip("\n").splitlines()],
    }


def _md_cell(source: str) -> dict:
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": [line + "\n" for line in source.strip("\n").splitlines()],
    }


def build_results_notebook_json() -> dict:
    cells = [
        _md_cell("""# HoleColor results explorer
This notebook is generated by the pipeline and is meant to be opened from the `notebooks/` folder inside a run output.
It loads the adjacent run artifacts and provides quick visual summaries for the hole-wise radial distribution function evolution, uncertainty, and sectorwise propagation."""),
        _code_cell("""from pathlib import Path
import json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display, Image

RUN_DIR = Path('..').resolve()
print('Run directory:', RUN_DIR)
"""),
        _code_cell("""def load_json(path):
    if not path.exists():
        return None
    with path.open('r', encoding='utf-8') as f:
        return json.load(f)

def load_csv(path):
    if not path.exists():
        return None
    return pd.read_csv(path)

summary = load_json(RUN_DIR / 'summary.json')
descriptor = load_json(RUN_DIR / 'descriptors' / 'descriptor_selection.json')
thresholds = load_json(RUN_DIR / 'qc' / 'threshold_envelope.json')
print('Summary:')
display(pd.DataFrame([summary]) if summary else pd.DataFrame())
print('Descriptor selection:')
display(pd.DataFrame([descriptor]) if descriptor else pd.DataFrame())
print('Threshold envelope:')
display(pd.DataFrame([thresholds]) if thresholds else pd.DataFrame())
"""),
        _code_cell("""rdf = load_csv(RUN_DIR / 'radial' / 'per_hole_rdf_evolution.csv')
if rdf is not None and not rdf.empty:
    first_hole = int(rdf['hole_id'].dropna().iloc[0])
    sub = rdf[rdf['hole_id'] == first_hole].copy()
    pivot = sub.pivot_table(index='frame_id', columns='annulus_id', values='rdf_pdf', aggfunc='mean').sort_index()
    plt.figure(figsize=(8, 4))
    plt.imshow(pivot.values, aspect='auto', origin='lower')
    plt.colorbar(label='RDF PDF')
    plt.title(f'First-hole RDF evolution heatmap (hole {first_hole})')
    plt.xlabel('Annulus')
    plt.ylabel('Frame')
    plt.tight_layout()
    plt.show()
else:
    print('No per_hole_rdf_evolution.csv found')
"""),
        _code_cell("""vel = load_csv(RUN_DIR / 'radial' / 'per_hole_rdf_velocity_summary.csv')
if vel is not None and not vel.empty:
    display(vel.head())
    plt.figure(figsize=(8, 4))
    plt.bar(vel['hole_id'].astype(str), vel['front_velocity'].fillna(0.0))
    plt.title('Per-hole RDF front velocity')
    plt.xlabel('Hole id')
    plt.ylabel('Front velocity')
    plt.xticks(rotation=90)
    plt.tight_layout()
    plt.show()
else:
    print('No per_hole_rdf_velocity_summary.csv found')
"""),
        _code_cell("""boot = load_csv(RUN_DIR / 'radial' / 'per_hole_rdf_bootstrap_summary.csv')
if boot is not None and not boot.empty:
    cols = [c for c in ['hole_id', 'bootstrap_front_velocity_mean', 'bootstrap_front_velocity_ci_width', 'bootstrap_front_radius_ci_width'] if c in boot.columns]
    display(boot[cols].head())
    if 'bootstrap_front_velocity_ci_width' in boot.columns:
        plt.figure(figsize=(8, 4))
        plt.bar(boot['hole_id'].astype(str), boot['bootstrap_front_velocity_ci_width'].fillna(0.0))
        plt.title('Per-hole RDF velocity uncertainty')
        plt.xlabel('Hole id')
        plt.ylabel('95% CI width')
        plt.xticks(rotation=90)
        plt.tight_layout()
        plt.show()
else:
    print('No bootstrap summary found')
"""),
        _code_cell("""for rel in [
    ('radial', 'rdf_uncertainty_reticulum_map.png'),
    ('radial', 'sector_front_acceleration.png'),
    ('radial', 'sector_front_propagation.png'),
    ('qc', 'radial_perturbation_drift_map.png'),
    ('temporal', 'phenotype_reticulum_map.png'),
]:
    path = RUN_DIR.joinpath(*rel)
    if path.exists():
        print(path.name)
        display(Image(filename=str(path)))
"""),
        _code_cell("""sector = load_csv(RUN_DIR / 'radial' / 'sector_front_propagation_hole_summary.csv')
if sector is not None and not sector.empty:
    display(sector.head())
    ycol = 'sector_propagation_anisotropy' if 'sector_propagation_anisotropy' in sector.columns else sector.columns[-1]
    plt.figure(figsize=(8, 4))
    plt.bar(sector['hole_id'].astype(str), sector[ycol].fillna(0.0))
    plt.title(f'Per-hole sector propagation summary: {ycol}')
    plt.xlabel('Hole id')
    plt.ylabel(ycol)
    plt.xticks(rotation=90)
    plt.tight_layout()
    plt.show()
else:
    print('No sector propagation summary found')
"""),
    ]
    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.x"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }


def write_results_notebook(out_dir: Path) -> Path:
    notebook_dir = Path(out_dir) / 'notebooks'
    notebook_dir.mkdir(parents=True, exist_ok=True)
    out_path = notebook_dir / 'holecolor_results_explorer.ipynb'
    out_path.write_text(json.dumps(build_results_notebook_json(), indent=2), encoding='utf-8')
    return out_path
